django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include

#conifg url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_base.urls')),
    path('account/', include('shop_account.urls')),
    path('product/', include('shop_product.urls')),
    path('', include('shop_contact.urls')),
    path('article/', include('shop_article.urls')),
    path('user-panel/', include('shop_admin_user.urls')),
    path('order/', include('shop_order.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#
# if settings.DEBUG:
#     urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns

django_shop/shop_article/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, add_article_comment

urlpatterns = [
    path('', ArticleListView.as_view(), name= 'article_page'),
    path('cat/<str:category>', ArticleListView.as_view(), name= 'article_category_page'),
path('add-article-comment', add_article_comment , name='add_article_comment_page'),
    path('<pk>', ArticleDetailView.as_view(), name= 'article_detail_page'),
]

django_shop/shop_base/urls.py
from django.urls import path
from .views import HomePageView, AboutUsView



urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('about-us', AboutUsView.as_view(), name='about_page'),
]

django_shop/shop_article/models.py
from django.db import models

from shop_Admin.models import User


class ArticleCategory(models.Model):
    title = models.CharField(max_length=150 )
    url_title = models.CharField(max_length=200, unique=True)
    parent = models.ForeignKey(to="ArticleCategory", on_delete=models.CASCADE, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title



class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, db_index=True, allow_unicode=True)
    short_description = models.TextField()
    description = models.TextField()
    selected_category = models.ManyToManyField(to='ArticleCategory', )
    image = models.ImageField(upload_to='images/articles')
    is_active = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, editable=False)
    add_time = models.DateTimeField(auto_now_add=True, editable=True)

    def __str__(self):
        return self.title


class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, )
    parent = models.ForeignKey("ArticleComment", on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    text = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.user)
        # return f'user : {self.user} || message for this article : {self.article}'

django_shop/shop_article/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic.list import ListView
from shop_article.models import Article, ArticleCategory, ArticleComment


class ArticleListView(ListView):
    model = Article
    template_name = 'article_shop/article.html'
    paginate_by = 4

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleListView, self).get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        query = super(ArticleListView, self).get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None :
            query = query.filter(selected_category__url_title__iexact=category_name)
        return query


class ArticleDetailView(DetailView) :
    model = Article
    template_name = 'article_shop/article_detail.html'

    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        id = self.kwargs.get('pk')
        query = query.filter(is_active=True)
        if query is not None:
            query = query.filter(id=id)
        return query

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        article: Article = kwargs.get('object')
        context['comments'] = ArticleComment.objects.filter(article_id= article.id, parent=None).order_by('-create_date').prefetch_related('articlecomment_set')
        return context

def category_article(request):
    main_category : ArticleCategory = ArticleCategory.objects.filter(is_active=True, parent=None)
    context = {
        'main_categories': main_category
    }
    return render(request, 'article_shop/article_component.html', context)


def add_article_comment(request: HttpRequest):
    if request.user.is_authenticated:
        article_id = request.GET.get('article_id')
        article_comment = request.GET.get('article_comment')
        parent_id = request.GET.get('parent_id')
        print(article_comment, article_id, parent_id)
        new_comment = ArticleComment(article_id=article_id, text=article_comment, user_id=request.user.id, parent_id=parent_id)
        new_comment.save()
        context = {
            'comments': ArticleComment.objects.filter(article_id= article_id, parent=None).order_by('-create_date').prefetch_related('articlecomment_set'),
            'comments_count': ArticleComment.objects.filter(article_id= article_id).count()
        }
        return render(request, 'article_shop/includes/article_comments_partial.html', context)

    return HttpResponse('response')

django_shop/shop_article/templates/article_shop/article.html
{% extends 'layout/base/base.html ' %}
{% load thumbnail %}
{% load poll_extras %}
{% load render_partial %}



{% block title %}
     Article
{% endblock %}

{% block body %}
    <section>
		<div class="container">
			<div class="row">
				
				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">آخریـن اخبـار</h2>
						{% for article in page_obj %}
                            <div class="single-blog-post">
							<h3>{{ article.title  }}</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i>{{ article.author }}</li>
									<li><i class="fa fa-clock-o"></i>{{ article.add_time | date_jalali  }}</li>
									<li><i class="fa fa-calendar"></i> 28 تیـر 1397</li>
								</ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
							</div>
                                {% thumbnail article.image "862x398" crop='center' as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}

                                <p>
                                    <br>
                                    {{ article.short_description }}
                                </p>
							<a class="btn btn-primary" href="{% url 'article_detail_page' pk=article.id %}">ادامـه مطلب</a>
						</div>

						{% endfor %}



                        <ul class="pagination">
                            <br>
                            {% if page_obj.has_previous %}
                                <li class=""><a href="?page={{ page_obj.previous_page_number }}">previous</a></li>
                            {% endif %}

                            {% for pageNumber in paginator.page_range %}
                                <li class=" {% if page_obj.number == pageNumber %}
                                active
                                {% endif %}   "><a href="?page={{ pageNumber }}">{{ pageNumber }}</a></li>
                            {% endfor %}

                        {% if page_obj.has_next %}
                                <li class=""><a href="?page={{ page_obj.next_page_number }}">next</a></li>
                            {% endif %}
					</div>
				</div>
				
				<div class="col-sm-3">
					<div class="left-sidebar">
                        {% render_partial 'shop_article.views.category_article'  %}
						
						<div class="shipping text-center"><!--shipping-->
							<img src="/static/images/home/shipping.jpg" alt="">
						</div><!--/shipping-->
						
					</div>
				</div>
				
			</div>
		</div>
	</section>
{% endblock %}

django_shop/shop_article/templates/article_shop/article_component.html
<h2>دسته بندی مقالات</h2>
 <div class="panel-group category-products" id="accordian"><!--category-productsr-->
        {% for main_category in main_categories %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										{% if main_category.articlecategory_set.all %}
                                            <a data-toggle="collapse" data-parent="#accordian" href="#{{ main_category.url_title }}">
											    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
											    {{ main_category.title }}
										    </a>

                                        {% else %}

                                            <a  href="">
											    {{ main_category.title }}
										    </a>

										{% endif %}
									</h4>
								</div>
								{% if main_category.articlecategory_set.all %}
								<div id="{{ main_category.url_title }}" class="panel-collapse collapse">
									<div class="panel-body">

                                        {% for sub_category in main_category.articlecategory_set.all %}
                                            <ul>
                                                <li><a href="{% url 'article_category_page' category=main_category.url_title %}">
                                                    {{ sub_category.title }}
                                                </a></li>
                                            </ul>
                                        {% endfor %}



									</div>
								</div>
								{% endif %}
							</div>
        {% endfor %}

						</div><!--/category-productsr-->

django_shop/shop_article/templates/article_shop/article_detail.html
{% extends 'layout/base/base.html' %}
{% load render_partial %}
{% load poll_extras %}
{% load thumbnail %}
{% block title %}

{% endblock %}

{% block body %}
    <section>
		<div class="container">
			<div class="row">

				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">{{ object.title }}</h2>
						<div class="single-blog-post">
							<h3>{{ object.title }}</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i>{{ object.author }}</li>
									<li><i class="fa fa-clock-o"></i>{{ object.add_time | time_jalali }}</li>
									<li><i class="fa fa-calendar"></i>{{ article.add_time | date_jalali }}</li>
								</ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
							</div>

								 <div>
                                     {% thumbnail article.image "862x398" crop='center' as im %}
                                        <img src="{{ im.url }}">
                                    {% endthumbnail %}
                                 </div>
                            <br>
							{{ object.description }}
							<div class="pager-area">
								<ul class="pager pull-left">
									<li><a href="#">قبلی</a></li>
									<li><a href="#">بعـدی</a></li>
								</ul>
							</div>
						</div>
					</div><!--/blog-post-area-->

					<div class="rating-area">
						<ul class="ratings">
							<li class="rate-this">به این مطلب امتیـاز دهیـد :</li>
							<li>
								<i class="fa fa-star color"></i>
								<i class="fa fa-star color"></i>
								<i class="fa fa-star color"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
							</li>
							<li class="color">( 6 نظـر )</li>
						</ul>
						<ul class="tag">
							<li>برچسب :</li>
							<li><a class="color" href="">برچسب 1 <span>/</span></a></li>
							<li><a class="color" href="">برچسب 2 <span>/</span></a></li>
							<li><a class="color" href="">برچسب 3</a></li>
						</ul>
					</div><!--/rating-area-->

					<div class="socials-share">
						<a href=""><img src="/static/images/blog/socials.png" alt=""></a>
					</div><!--/socials-share-->

					<div class="media commnets">
                        <div>
                            {% thumbnail object.author.avatar "121x86" crop='center' as im %}
                                <img class="media_object" src="{{ im.url }}">

                            {% endthumbnail %}

                        </div>
                    <br>
						<div class="media-body">
							<h4 class="media-heading">{{ object.author.username }}</h4>
                            <p>
                                {{ object.author.about_user }}
                            </p>
							<div class="blog-socials">
								<ul>
									<li><a href=""><i class="fa fa-facebook"></i></a></li>
									<li><a href=""><i class="fa fa-twitter"></i></a></li>
									<li><a href=""><i class="fa fa-dribbble"></i></a></li>
									<li><a href=""><i class="fa fa-google-plus"></i></a></li>
								</ul>
								<a class="btn btn-primary" href="">سایـر مطالب نویسنده</a>
							</div>
						</div>
					</div><!--Comments-->
					<div class="response-area" id="comments_area">
						<h2> نظرات ({{  comments.count }})</h2>
						<ul class="media-list">
							{% for comment in comments %}
                                <li class="media">

								<a class="pull-right" href="#">
									{% thumbnail comment.user.avatar "121x86" crop='center' as im %}
                                         <img class="media_object" src="{{ im.url }}">

                                     {% endthumbnail %}
								</a>

								<div class="media-body">
									<ul class="sinlge-post-meta">
										<li><i class="fa fa-user"></i>{{ comment.user }}</li>
										<li><i class="fa fa-clock-o"></i>  {{ comment.create_date | time}}</li>
										<li><i class="fa fa-calendar"></i>{{ comment.create_date | date_jalali }}</li>
									</ul>
									<p>
                                        {{ comment.text }}
                                    </p>
                                        <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i class="fa fa-reply"></i>پاسـخ</a>
								</div>
							</li>

                                {% for sun_comment in comment.articlecomment_set.all %}
                                    <li class="media second-media">
								<a class="pull-right" href="#">
									{% thumbnail sun_comment.user.avatar "121x86" crop='center' as im %}
                                         <img class="media_object" src="{{ im.url }}">

                                     {% endthumbnail %}
								</a>
								<div class="media-body">
									<ul class="sinlge-post-meta">
										<li><i class="fa fa-user"></i>  {{ sun_comment.user }}</li>
										<li><i class="fa fa-clock-o"></i>  {{ sun_comment.create_date | time }}</li>
										<li><i class="fa fa-calendar"></i>{{ sun_comment.create_date | date_jalali }}</li>
									</ul>
                                    <p>
                                        {{ sun_comment.text }}
                                    </p>
								</div>
							</li>
                                {% endfor %}


							{% endfor %}


                            <br>

						</ul>
					</div><!--/Response-area-->

                        <div class="replay-box" id="comment_form">
                            {% if request.user.is_authenticated %}
						<div class="row">

							<div class="col-sm-12">
                                <h2>نظـر خود را بنویسیـد</h2>
								<div class="text-area"  >
                                    <input type="hidden"  id="parent_id" value="">
									<div class="blank-arrow">
										<label>متن پیام</label>
									</div>
									<span>*</span>
									<textarea name="message" rows="11" id="commentText"></textarea>
									<a class="btn btn-primary" onclick="sendArticleComment({{ article.id }})">ارسـال نظـر</a>
								</div>
							</div>
						</div>
                            {% else %}
                        <div class="alert alert-warning">
                            for send message should be <a href="{% url 'login_page' %}">login</a> .
                            {% endif %}
					</div><!--/Repaly Box-->


                 <br>
				</div>

				<div class="col-sm-3">
					<div class="left-sidebar">

                            {% render_partial 'shop_article.views.category_article' %}




					</div>
				</div>

			</div>
		</div>
	</section>
{% endblock %}